language: node_js
node_js:
  - "4.3.2"

script: 'npm run cover'

after_success: 'npm run coveralls'

deploy:
  provider: script
  script: "./scripts/deploy.sh" staging
  skip-cleanup: true
  on:
    branch: feature/continuous-deployment

cache:
  directories:
      - node_modules

notifications:
  slack: messengerbot:GrfKpxLfW17ZRAirqXjuqNfh
