service: coaching-chatbot

provider:
  name: aws
  runtime: nodejs4.3

functions:
  facebookMessenger:
    handler: facebook-messenger/handler.handler
    memorySize: 128
    timeout: 15
    events:
      - http:
          path: facebook-bot
          method: get
          integration: lambda
          response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$.response')
      - http:
          path: facebook-bot
          method: post
          integration: lambda

plugins:
  - serverless-webpack
